'use client'

import { motion, useInView } from 'framer-motion'
import { ArrowRight, Brain, Building2, Shield } from 'lucide-react'
import Link from 'next/link'
import { useRef } from 'react'

import { LogoWithText } from '@/components/brand'
import { Button } from '@/components/ui/button'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'

const features = [
  {
    icon: Building2,
    title: 'Multi-Hospital Data',
    description:
      'Connect and view your medical records from multiple healthcare providers in one unified dashboard.',
    featured: false,
  },
  {
    icon: Brain,
    title: 'AI-Powered Summaries',
    description:
      'Get intelligent summaries of your health data with actionable insights generated by advanced AI. Our system analyzes patterns across all your records to surface what matters most.',
    featured: true,
  },
  {
    icon: Shield,
    title: 'Secure Sharing',
    description:
      'Share your records securely with new providers using time-limited access links you control.',
    featured: false,
  },
]

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.15,
    },
  },
}

const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: {
    opacity: 1,
    y: 0,
    transition: {
      duration: 0.5,
      ease: 'easeOut' as const,
    },
  },
}

const cardVariants = {
  hidden: { opacity: 0, y: 30 },
  visible: {
    opacity: 1,
    y: 0,
    transition: {
      duration: 0.6,
      ease: 'easeOut' as const,
    },
  },
}

function FeatureCard({
  feature,
  index,
}: {
  feature: (typeof features)[0]
  index: number
}) {
  const ref = useRef(null)
  const isInView = useInView(ref, { once: true, margin: '-50px' })

  return (
    <motion.div
      ref={ref}
      variants={cardVariants}
      initial="hidden"
      animate={isInView ? 'visible' : 'hidden'}
      transition={{ delay: index * 0.1 }}
      className={feature.featured ? 'md:col-span-2 md:row-span-2' : ''}
    >
      <Card
        className={`card-hover h-full border-border/50 bg-card/80 ${
          feature.featured
            ? 'bg-gradient-to-br from-primary/5 via-card to-card'
            : ''
        }`}
      >
        <CardHeader className={feature.featured ? 'pb-4' : ''}>
          <div
            className={`mb-2 flex items-center justify-center rounded-lg bg-primary/10 ${
              feature.featured ? 'size-16' : 'size-12'
            }`}
          >
            <feature.icon
              className={`text-primary ${feature.featured ? 'size-8' : 'size-6'}`}
              aria-hidden="true"
            />
          </div>
          <CardTitle className={feature.featured ? 'text-2xl' : 'text-lg'}>
            {feature.title}
          </CardTitle>
        </CardHeader>
        <CardContent>
          <CardDescription
            className={`leading-relaxed ${feature.featured ? 'text-base' : 'text-sm'}`}
          >
            {feature.description}
          </CardDescription>
        </CardContent>
      </Card>
    </motion.div>
  )
}

export default function LandingPage() {
  const featuresRef = useRef(null)
  const featuresInView = useInView(featuresRef, {
    once: true,
    margin: '-100px',
  })

  return (
    <div className="flex min-h-screen flex-col">
      {/* Header */}
      <header className="flex items-center justify-between border-b px-6 py-4">
        <LogoWithText size={36} className="text-foreground" />
        <nav className="flex gap-4">
          <Button asChild variant="ghost" size="sm">
            <Link href="/patient/login">Patient Login</Link>
          </Button>
          <Button asChild variant="outline" size="sm">
            <Link href="/provider">Provider Portal</Link>
          </Button>
        </nav>
      </header>

      {/* Hero Section with background pattern */}
      <main className="relative flex flex-1 flex-col items-center justify-center overflow-hidden px-6 py-24">
        {/* Subtle background gradient */}
        <div className="absolute inset-0 -z-10 bg-gradient-to-b from-primary/[0.03] via-transparent to-transparent" />
        {/* Subtle grid pattern */}
        <div
          className="absolute inset-0 -z-10 opacity-[0.015]"
          style={{
            backgroundImage: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23000000' fill-opacity='1'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E")`,
          }}
        />

        <motion.div
          className="mx-auto max-w-4xl text-center"
          variants={containerVariants}
          initial="hidden"
          animate="visible"
        >
          <motion.h1
            variants={itemVariants}
            className="heading-accent mx-auto mb-6 max-w-3xl text-balance text-4xl font-semibold tracking-tight sm:text-5xl lg:text-6xl"
          >
            Your Health Data, Unified
          </motion.h1>
          <motion.p
            variants={itemVariants}
            className="mx-auto mb-10 max-w-2xl text-pretty text-lg text-muted-foreground sm:text-xl"
          >
            Evexia aggregates your medical records from multiple hospitals into
            one secure platform. Access your complete health history, get
            AI-powered insights, and share with providers on your terms.
          </motion.p>
          <motion.div
            variants={itemVariants}
            className="flex flex-col items-center justify-center gap-4 sm:flex-row"
          >
            <Button asChild size="lg" className="w-full sm:w-auto">
              <Link href="/patient/login">
                Patient Login
                <ArrowRight className="ml-2 size-4" aria-hidden="true" />
              </Link>
            </Button>
            <Button
              asChild
              variant="outline"
              size="lg"
              className="w-full sm:w-auto"
            >
              <Link href="/provider">Provider Portal</Link>
            </Button>
          </motion.div>
        </motion.div>
      </main>

      {/* Features Section with bento grid */}
      <section className="border-t bg-muted/30 px-6 py-20">
        <div className="mx-auto max-w-5xl">
          <motion.h2
            ref={featuresRef}
            initial={{ opacity: 0, y: 20 }}
            animate={featuresInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.5 }}
            className="mb-12 text-center text-3xl font-semibold tracking-tight"
          >
            Why Choose Evexia
          </motion.h2>
          {/* Asymmetric bento layout: AI-Powered Summaries spans 2 cols on md+ */}
          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
            {/* First feature - normal size */}
            <FeatureCard feature={features[0]} index={0} />
            {/* Second feature (AI) - featured, larger */}
            <FeatureCard feature={features[1]} index={1} />
            {/* Third feature - normal size */}
            <FeatureCard feature={features[2]} index={2} />
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t px-6 py-8">
        <div className="mx-auto flex max-w-5xl flex-col items-center justify-between gap-4 text-sm text-muted-foreground sm:flex-row">
          <p suppressHydrationWarning>
            &copy; {new Date().getFullYear()} Evexia. All rights reserved.
          </p>
          <nav className="flex gap-6">
            <Link href="/privacy" className="hover:text-foreground">
              Privacy
            </Link>
            <Link href="/terms" className="hover:text-foreground">
              Terms
            </Link>
          </nav>
        </div>
      </footer>
    </div>
  )
}
